profile: null
region: us-east-1
versioning: false
default_alias: master
configuration:
  name: cfcache-invalidation
  runtime: python2.7
  role: {{ env['AWS_LAMBDA_ROLE'] }}
  handler: lambda_function.lambda_handler
  description: CloudFront Cache Invalidation
  timeout: 10
  memory_size: 128
